#!/usr/bin/env python3
"""Generates the command surface of `RedisPipeline` from fred's command interfaces.

Usage: python3 scripts/gen_pipeline_commands.py <path to fred's src directory>

Each forwarded method keeps fred's own signature, with the reply type fixed to `()`: a command
queued into a delivery's segment runs after the handler returns, so there is no reply to read.
Blocking commands, reads that stream, and commands that change the connection's state are left
out, because a segment shares its connection with the other segments of the window.
"""

import re
import sys
from pathlib import Path

INTERFACES = [
    ("keys.rs", "KeysInterface"),
    ("hashes.rs", "HashesInterface"),
    ("lists.rs", "ListInterface"),
    ("sets.rs", "SetsInterface"),
    ("sorted_sets.rs", "SortedSetsInterface"),
    ("streams.rs", "StreamsInterface"),
    ("lua.rs", "FunctionInterface"),
    ("pubsub.rs", "PubsubInterface"),
]

# Blocking commands would hold the window's connection, reads that stream have no place in a
# queue, and these change the state of the connection every segment of the window shares.
EXCLUDED = {
    "watch", "unwatch",
    "blpop", "brpop", "brpoplpush", "blmove", "blmpop",
    "bzpopmin", "bzpopmax", "bzmpop",
    "xread", "xread_map", "xreadgroup", "xreadgroup_map",
    "subscribe", "unsubscribe", "psubscribe", "punsubscribe", "ssubscribe", "sunsubscribe",
    "script_kill", "script_kill_cluster", "script_flush_cluster", "script_load_cluster",
    "script_debug", "function_kill", "function_delete_cluster", "function_flush_cluster",
    "function_load_cluster", "function_restore_cluster",
    "scan_page",
}

HEADER = """\
// Generated by scripts/gen_pipeline_commands.py from fred's command interfaces; regenerate rather
// than edit.

//! The commands a handler queues into its delivery's segment, one per fred command method.

// The summaries are fred's own prose, copied as it is written.
#![allow(clippy::too_many_arguments, clippy::missing_errors_doc, clippy::doc_markdown)]

use fred::bytes::Bytes;
use fred::bytes_utils::Str;
use fred::error::Error;
use fred::interfaces::{
    FunctionInterface, HashesInterface, KeysInterface, ListInterface, PubsubInterface,
    SetsInterface, SortedSetsInterface, StreamsInterface,
};
use fred::types::lists::{LMoveDirection, ListLocation};
use fred::types::scripts::FnPolicy;
use fred::types::sorted_sets::{
    AggregateOptions, MultipleWeights, MultipleZaddValues, Ordering, ZCmp, ZRange, ZSort,
};
use fred::types::streams::{MultipleIDs, MultipleOrderedPairs, XCap, XID, XPendingArgs};
use fred::types::{
    Expiration, ExpireOptions, Key, Limit, Map, MultipleKeys, MultipleStrings, MultipleValues,
    SetOptions, SortOrder, Value,
};

use super::{RedisPipeline, Segment};

impl RedisPipeline {
"""

FOOTER = "}\n"


def split_top(text, sep=","):
    """Splits `text` on `sep` at nesting depth zero."""
    parts, depth, cur = [], 0, []
    i = 0
    while i < len(text):
        c = text[i]
        if c == "-" and text[i:i + 2] == "->":
            cur.append("->")
            i += 2
            continue
        if c in "<([":
            depth += 1
        elif c in ">)]":
            depth -= 1
        if c == sep and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    last = "".join(cur).strip()
    if last:
        parts.append(last)
    return parts


def balanced(text, start, open_c, close_c):
    """Returns the index just past the bracket that closes the one at `start`."""
    depth = 0
    i = start
    while i < len(text):
        c = text[i]
        if c == "-" and text[i:i + 2] == "->":
            i += 2
            continue
        if c == open_c:
            depth += 1
        elif c == close_c:
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced")


def trait_body(source, trait):
    start = source.index(f"pub trait {trait}")
    open_brace = source.index("{", start)
    end = balanced(source, open_brace, "{", "}")
    return source[open_brace + 1:end - 1]


def methods(body):
    """Yields (doc, signature) for each method of a trait body that the enabled features keep."""
    lines = body.split("\n")
    doc, gated, i = [], False, 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if stripped.startswith("///"):
            doc.append(stripped[3:].strip())
            i += 1
            continue
        if stripped.startswith("#["):
            # A method behind a feature of fred's this crate does not enable is not there.
            if stripped.startswith("#[cfg(") and "docsrs" not in stripped:
                gated = True
            i += 1
            continue
        if line.startswith("  fn "):
            sig = [stripped]
            while not sig[-1].endswith("{"):
                i += 1
                sig.append(lines[i].strip())
            if not gated:
                yield doc, " ".join(sig)[:-1].strip()
            gated = False
            # Skip the body.
            depth = 1
            while depth:
                i += 1
                depth += lines[i].count("{") - lines[i].count("}")
            doc = []
        elif stripped and not stripped.startswith("//"):
            doc = []
        i += 1


def summary(doc):
    text = " ".join(line for line in doc if line and not line.startswith("<http"))
    text = text.split("```")[0]
    sentence = re.split(r"(?<=\.)\s", text, maxsplit=1)[0].strip()
    return sentence or "Queues the command."


def parse(signature):
    assert signature.startswith("fn ")
    rest = signature[3:]
    name = re.match(r"r#[a-z_0-9]+|[a-z_0-9]+", rest).group(0)
    rest = rest[len(name):]
    generics = []
    if rest.startswith("<"):
        end = balanced(rest, 0, "<", ">")
        generics = split_top(rest[1:end - 1])
        rest = rest[end:]
    end = balanced(rest, 0, "(", ")")
    params = split_top(rest[1:end - 1])
    rest = rest[end:].strip()
    assert rest.startswith("->"), signature
    rest = rest[2:].strip()
    where = []
    if " where " in f" {rest} ":
        ret, clause = re.split(r"\bwhere\b", rest, maxsplit=1)
        where = split_top(clause.strip().rstrip(","))
    else:
        ret = rest
    return name, generics, params, ret.strip(), where


def render(doc, signature):
    name, generics, params, ret, where = parse(signature)
    if name in EXCLUDED:
        return None
    output = re.match(r"impl Future<Output = FredResult<(.*)>> \+ Send$", ret)
    if not output:
        return None
    reply = output.group(1).strip()
    # A command whose reply fred parses into a structure of its own is a read, and a queued read
    # has no reply to parse.
    if reply != "()" and reply not in generics:
        return None
    args = [p.split(":")[0].strip() for p in params if not p.startswith("&self")]
    kept = [g for g in generics if g != reply]
    turbofish = ""
    if reply in generics:
        turbofish = "::<" + ", ".join("()" if g == reply else g for g in generics) + ">"
    clauses = [w for w in where if not w.startswith(f"{reply}:")]
    lines = [f"    /// {summary(doc)}", "    ///",
             "    /// Queued into this delivery's segment; it runs after the handler returns, when",
             "    /// the delivery is acknowledged."]
    head = f"    pub async fn {name}"
    if kept:
        head += "<" + ", ".join(kept) + ">"
    head += "(" + ", ".join(params) + ") -> Result<(), Error>"
    lines.append(head)
    if clauses:
        lines.append("    where")
        lines.extend(f"        {c}," for c in clauses)
    call = f"{name}{turbofish}(" + ", ".join(args) + ")"
    discard = "" if reply in generics or reply == "()" else ".map(|_| ())"
    lines.append("    {")
    lines.append("        match self.segment()? {")
    lines.append(f"            Segment::Plain(segment) => segment.{call}.await{discard},")
    lines.append(f"            Segment::Atomic(segment) => segment.{call}.await{discard},")
    lines.append("        }")
    lines.append("    }")
    return "\n".join(lines)


def main():
    src = Path(sys.argv[1]) / "commands" / "interfaces"
    out = [HEADER]
    seen = set()
    for file, trait in INTERFACES:
        body = trait_body((src / file).read_text(), trait)
        for doc, signature in methods(body):
            rendered = render(doc, signature)
            name = parse(signature)[0]
            if rendered and name not in seen:
                seen.add(name)
                out.append(rendered)
                out.append("")
    out.append(FOOTER)
    target = Path(__file__).resolve().parent.parent / "crates" / "ruststream-fred" / "src" / "pipeline" / "commands.rs"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out))
    print(f"{len(seen)} commands written to {target}")


if __name__ == "__main__":
    main()
